name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  job_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pyTelegramBotAPI
        python -m pip install requests
        pip install pyrogram
        pip install asyncio
        pip install tgintegration --upgrad
        
  job_test_unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test get/set
      run: 
        python testSession.py
        
  job_test_integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test of one-player case
      run: 
        python integrationTest.py
